### ISSUE TITLE
Support  HTTP OPTIONS method

### ISSUE THREAD

**Issue by nichtich** [nichtich/Plack-Middleware-REST#4]
Based on the configuration it should be possible to automatically generate the response to an [HTTP OPTIONS](http://tools.ietf.org/html/draft-ietf-httpbis-p2-semantics-21#section-5.3.7) request, listing the allowed HTTP methods for an URL, e.g. on `/` (if both `create` and `list` are configured):

    Allow: GET,HEAD,POST,OPTIONS

**Comment by cakirke** [comment]
while researching possibilities for issue #6 found i missed actually listing OPTIONS in the Allow: header when it is enabled, another pull request is in the works
