### ISSUE TITLE
Support HTTP PATCH method

### ISSUE THREAD

**Issue by nichtich** [nichtich/Plack-Middleware-REST#6]
This makes only sense on existing resources, so an additional `patch` configuration parameter should be enough.

**Comment by cakirke** [comment]
per http://tools.ietf.org/html/rfc5789 looks like we'll need to allow definition of patch formats, possibly via Plack::Middleware::Negotiate as well as configuration using Plack::Middleware::ETag

**Comment by nichtich** [comment]
Do you refer to the `Accept-Patch` Header in a OPTIONS response? I suppose that the list is static for most applications. A code reference that maps PSGI request to a list of patch formats would be enough and the header field is optional anyway. All other parts of PATCH should better be handled in the app that Plack::Middleware::REST routes to, possibly with middleware (#9).

**Comment by cakirke** [comment]
yes, referring to Accept-Patch header - sounds like this would be sufficient (default = PATCH not enabled), i think this follows your very first comment in this issue:

builder {
        enable 'REST',
            get          => $get,      # HTTP GET on a resource
            create       => $create,   # HTTP POST in '/'
            upsert       => $update,   # HTTP PUT on a resource
            list         => $list,     # HTTP GET on '/'
            pass_through => 1,         # pass if no defined REST request
            patch  =>  [ 'application/xml' ];   # array of acceptable patch types
        $app;
    };

would be invalid to define patch without upsert

**Comment by nichtich** [comment]
patch types are optional, so better this

```perl
builder {
  enable 'REST',
    get => $get, # HTTP GET on a resource
    create => $create, # HTTP POST in '/'
    upsert => $update, # HTTP PUT on a resource
    list => $list, # HTTP GET on '/'
    pass_through => 1, # pass if no defined REST request
    patch => $patch, # PATCH on a resource
    patch_types => [ 'application/xml' ]; # array of acceptable patch types
    $app;
};
```

Sure one could also set patch to `upsert` to use the same sub for both requests.
